import initSqlJs from 'sql.js';
import { readFileSync, existsSync } from 'node:fs';
import { validateTypeScript } from './validator.js';
import {
  canCreatePr,
  createBranch,
  commitAndPush,
  openPr,
  returnToMainBranch,
} from '../github/pr-manager.js';

interface AuditIssue {
  id: number;
  url: string;
  issue_type: string;
  severity: string;
  description: string;
  suggested_fix: string | null;
  fix_status: string;
}

interface PipelineConfig {
  dbPath: string;
  projectDir: string;
}

interface PipelineResult {
  processed: number;
  fixed: number;
  failed: number;
  skipped: number;
  prsCreated: string[];
}

export async function runAutoFixPipeline(config: PipelineConfig): Promise<PipelineResult> {
  const result: PipelineResult = {
    processed: 0,
    fixed: 0,
    failed: 0,
    skipped: 0,
    prsCreated: [],
  };

  const SQL = await initSqlJs();
  if (!existsSync(config.dbPath)) {
    console.log('No database found at', config.dbPath);
    return result;
  }

  const buffer = readFileSync(config.dbPath);
  const db = new SQL.Database(buffer);

  // Get open audit issues with suggested fixes
  const issues = db.exec(
    `SELECT id, url, issue_type, severity, description, suggested_fix, fix_status
     FROM audit_issues
     WHERE fix_status = 'open' AND suggested_fix IS NOT NULL
     ORDER BY
       CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
       detected_at ASC`
  );

  if (!issues.length || !issues[0].values.length) {
    console.log('No open audit issues with suggested fixes.');
    db.close();
    return result;
  }

  const rows: AuditIssue[] = issues[0].values.map((row) => ({
    id: row[0] as number,
    url: row[1] as string,
    issue_type: row[2] as string,
    severity: row[3] as string,
    description: row[4] as string,
    suggested_fix: row[5] as string | null,
    fix_status: row[6] as string,
  }));

  for (const issue of rows) {
    result.processed++;

    // Check PR limit before each fix
    if (!canCreatePr(config.projectDir)) {
      console.log(`Max open SEO PRs reached. Skipping remaining issues.`);
      result.skipped += rows.length - result.processed + 1;
      break;
    }

    if (!issue.suggested_fix) {
      result.skipped++;
      continue;
    }

    console.log(`Processing: [${issue.severity}] ${issue.issue_type} on ${issue.url}`);

    // Validate the suggested fix with tsc --noEmit
    const validation = validateTypeScript(issue.suggested_fix, config.projectDir);

    if (!validation.valid) {
      console.log(`  Type errors — rolling back. Errors: ${validation.errors.join('; ')}`);
      db.run(`UPDATE audit_issues SET fix_status = 'open' WHERE id = ?`, [issue.id]);
      result.failed++;
      continue;
    }

    // Create branch, commit, push, open PR
    try {
      const slug = issue.url.replace(/[^a-z0-9]/gi, '-').slice(0, 30);
      const branchName = createBranch(config.projectDir, issue.issue_type, slug);

      // The validated fix would be applied to the actual file here
      // For now we commit the suggested fix as a patch file
      const patchFile = `fixes/${issue.issue_type}-${issue.id}.ts`;
      commitAndPush(config.projectDir, branchName, `fix(seo): ${issue.issue_type} on ${issue.url}`, [patchFile]);

      const prUrl = openPr(
        config.projectDir,
        `fix(seo): ${issue.issue_type} — ${issue.url}`,
        `## SEO Auto-Fix\n\n- **Issue**: ${issue.description}\n- **Severity**: ${issue.severity}\n- **URL**: ${issue.url}\n- **Validated**: tsc --noEmit passed\n\n> Auto-generated by AutoFix Deploy Engineer. Requires human review before merge.`,
        branchName
      );

      db.run(`UPDATE audit_issues SET fix_status = 'in_progress', pr_url = ? WHERE id = ?`, [prUrl, issue.id]);
      result.fixed++;
      result.prsCreated.push(prUrl);

      returnToMainBranch(config.projectDir);
    } catch (err: any) {
      console.log(`  PR creation failed: ${err.message}`);
      returnToMainBranch(config.projectDir);
      result.failed++;
    }
  }

  // Record pipeline run
  db.run(
    `INSERT INTO agent_runs (agent_name, run_type, status, items_processed, items_failed, summary)
     VALUES (?, ?, ?, ?, ?, ?)`,
    [
      'autofix-deploy-engineer',
      'auto_fix_pipeline',
      result.failed === 0 ? 'success' : 'failure',
      result.processed,
      result.failed,
      `Fixed: ${result.fixed}, Failed: ${result.failed}, Skipped: ${result.skipped}`,
    ]
  );

  // Save DB
  const { writeFileSync } = await import('node:fs');
  const data = db.export();
  writeFileSync(config.dbPath, Buffer.from(data));
  db.close();

  console.log(`Pipeline complete: ${result.fixed} fixed, ${result.failed} failed, ${result.skipped} skipped`);
  return result;
}

// CLI entry point
const dbPath = process.argv[2] || 'seo_pipeline.db';
const projectDir = process.argv[3] || '.';

runAutoFixPipeline({ dbPath, projectDir }).catch(console.error);
