import { type Database } from 'sql.js';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  canCreatePr,
  createBranch,
  commitAndPush,
  openPr,
  returnToMainBranch,
} from '../github/pr-manager.js';

interface GeoDeployConfig {
  projectDir: string;
  publicDir: string;
  siteUrl: string;
  siteName: string;
}

interface LlmsTxtEntry {
  url: string;
  title: string;
  description: string;
}

/**
 * Generates llms.txt content following the llms.txt specification.
 * This file helps AI crawlers understand the site structure.
 */
export function generateLlmsTxt(
  siteName: string,
  siteUrl: string,
  entries: LlmsTxtEntry[]
): string {
  const lines: string[] = [
    `# ${siteName}`,
    '',
    `> ${siteName} — AI-friendly site map`,
    '',
  ];

  for (const entry of entries) {
    lines.push(`- [${entry.title}](${siteUrl}${entry.url}): ${entry.description}`);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Builds llms.txt entries from geo_scores and content_suggestions tables.
 */
export function buildEntriesFromDb(db: Database): LlmsTxtEntry[] {
  const results = db.exec(`
    SELECT DISTINCT gs.url, cs.title, cs.body
    FROM geo_scores gs
    LEFT JOIN content_suggestions cs ON cs.url = gs.url AND cs.status = 'accepted'
    ORDER BY gs.score DESC
    LIMIT 200
  `);

  if (!results.length) return [];

  return results[0].values.map((row) => ({
    url: row[0] as string,
    title: (row[1] as string) || (row[0] as string),
    description: (row[2] as string) || '',
  }));
}

/**
 * Deploys llms.txt to the webapp public directory via a PR.
 */
export function deployLlmsTxt(
  config: GeoDeployConfig,
  content: string
): { prUrl: string } | { skipped: string } {
  if (!canCreatePr(config.projectDir)) {
    return { skipped: 'Max open SEO PRs reached' };
  }

  const filePath = join(config.publicDir, 'llms.txt');
  writeFileSync(filePath, content, 'utf-8');

  const branchName = createBranch(config.projectDir, 'geo', `llms-txt-${Date.now()}`);

  commitAndPush(config.projectDir, branchName, 'chore(seo): update llms.txt for AI crawlers', [filePath]);

  const prUrl = openPr(
    config.projectDir,
    'chore(seo): weekly llms.txt update',
    '## GEO Artifact Deploy\n\nUpdated `llms.txt` with latest site content map for AI crawlers.\n\n> Auto-generated by AutoFix Deploy Engineer. Requires human review before merge.',
    branchName
  );

  returnToMainBranch(config.projectDir);

  return { prUrl };
}
