import { type Database } from 'sql.js';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import {
  canCreatePr,
  createBranch,
  commitAndPush,
  openPr,
  returnToMainBranch,
} from '../github/pr-manager.js';

interface LinkSuggestion {
  id: number;
  source_url: string;
  target_url: string;
  suggested_anchor_text: string;
  reason: string;
  priority: string;
}

interface LinkDeployConfig {
  projectDir: string;
  suggestionsDir: string;
}

/**
 * Fetches pending link suggestions from the database.
 */
export function getPendingLinkSuggestions(db: Database): LinkSuggestion[] {
  const results = db.exec(`
    SELECT id, source_url, target_url, suggested_anchor_text, reason, priority
    FROM link_suggestions
    WHERE status = 'pending'
    ORDER BY
      CASE priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
      created_at ASC
  `);

  if (!results.length) return [];

  return results[0].values.map((row) => ({
    id: row[0] as number,
    source_url: row[1] as string,
    target_url: row[2] as string,
    suggested_anchor_text: row[3] as string,
    reason: row[4] as string,
    priority: row[5] as string,
  }));
}

/**
 * Generates a JSON manifest of link suggestions for review.
 */
export function generateLinkManifest(suggestions: LinkSuggestion[]): string {
  const manifest = {
    generatedAt: new Date().toISOString(),
    totalSuggestions: suggestions.length,
    suggestions: suggestions.map((s) => ({
      sourceUrl: s.source_url,
      targetUrl: s.target_url,
      anchorText: s.suggested_anchor_text,
      reason: s.reason,
      priority: s.priority,
    })),
  };

  return JSON.stringify(manifest, null, 2);
}

/**
 * Deploys link suggestions as a JSON manifest via PR.
 */
export function deployLinkSuggestions(
  config: LinkDeployConfig,
  suggestions: LinkSuggestion[],
  db: Database
): { prUrl: string } | { skipped: string } {
  if (!canCreatePr(config.projectDir)) {
    return { skipped: 'Max open SEO PRs reached' };
  }

  if (suggestions.length === 0) {
    return { skipped: 'No pending link suggestions' };
  }

  const manifest = generateLinkManifest(suggestions);
  const manifestPath = join(config.suggestionsDir, `link-suggestions-${Date.now()}.json`);
  writeFileSync(manifestPath, manifest, 'utf-8');

  const branchName = createBranch(config.projectDir, 'links', `suggestions-${Date.now()}`);

  commitAndPush(
    config.projectDir,
    branchName,
    `chore(seo): deploy ${suggestions.length} link suggestions`,
    [manifestPath]
  );

  const prUrl = openPr(
    config.projectDir,
    `chore(seo): ${suggestions.length} internal link suggestions`,
    `## Link Suggestions Deploy\n\n- **Total suggestions**: ${suggestions.length}\n- **High priority**: ${suggestions.filter((s) => s.priority === 'high').length}\n- **Medium priority**: ${suggestions.filter((s) => s.priority === 'medium').length}\n\nReview the JSON manifest and apply relevant links.\n\n> Auto-generated by AutoFix Deploy Engineer. Requires human review before merge.`,
    branchName
  );

  // Mark suggestions as accepted in DB
  for (const s of suggestions) {
    db.run(`UPDATE link_suggestions SET status = 'accepted' WHERE id = ?`, [s.id]);
  }

  returnToMainBranch(config.projectDir);

  return { prUrl };
}
